language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
cache:
  directories:
    - $HOME/.cache/pip
before_install:
  - pip install setuptools pip pytest --upgrade
install:
  - pip install -e .[dev]
script:
  - make check html-docs
