language: python
python:
  - "2.7"
  - "3.4"
cache:
  directories:
    - $HOME/.cache/pip
before_install:
  - pip install setuptools pip --upgrade
install:
  - pip install -e .[dev]
script:
  - make check html-docs
