site_name: Planet SDK for Python
site_description: Python client library for Planet's APIs.
site_url: https://planetlabs.github.io/planet-client-python/

theme:
    name: 'material'

repo_name: planetlabs/planet-client-python
repo_url: https://github.com/planetlabs/planet-client-python
edit_uri: ""

nav:
    - Introduction: 'index.md'

markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
  - mkautodoc
